version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: daily
      time: "22:00"
    open-pull-requests-limit: 10
    
