version: 2.0.0.{build}
pull_requests:
  do_not_increment_build_number: true
image:
# - Visual Studio 2019
- Ubuntu2004
configuration: Appveyor
platform: x64
nuget:
  project_feed: true
before_build:
- pwsh: dotnet restore
build:
  parallel: true
  verbosity: minimal
deploy: off