version: 2.0.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image:
- Ubuntu
- Visual Studio 2022
configuration: Appveyor
platform: x64
environment:
  GH_TOKEN:
    secure: vDDcxUMbqWehTBZmMLBOdkLPy91l30JeZuy124fVsiMomzvAy+u7VPleqhSCWIzJCHDs+vTeNBM1TkllUtkmgqG4EZrbdDmLyrSc03vO0jAUZh/cBjaFCchz1IAf5F6B
  NUGET_API_KEY:
    secure: TckP2JYCNhvzczhWFFbEHGX7nkSaMxPYY7xmgSqbt3CJzu33sPpZy2gKt6F/FYez
before_build:
- pwsh: dotnet restore
build:
  parallel: true
  verbosity: minimal
# before_deploy:
after_test: 
- pwsh: ./publish-github-release.ps1
artifacts:
- path: GTiff2Tiles.Core\bin\x64\Release\*.nupkg
  name: nupkg
- path: GTiff2Tiles.Core\bin\x64\Release\*.snupkg
  name: snupkg
- path: Publish\*.zip
  name: zip
deploy:
- provider: GitHub
  release: Continious build
  description: This is a preview release of GTiff2Tiles ver. 2.0.0. Information about changes since previous release can be found in [changelog](https://github.com/Gigas002/GTiff2Tiles/blob/master/CHANGELOG.md).
  auth_token: $(GH_TOKEN)
  artifact: /.*\.zip/
  draft: false
  prerelease: true
  force_update: true
  on:
    branch: master
- provider: NuGet
  api_key: $(NUGET_API_KEY)
  artifact: /.*(\.|\.s)nupkg/
  on:
    branch: master
- provider: NuGet
  server: https://nuget.pkg.github.com/gigas002/index.json
  api_key: $(GH_TOKEN)
  username:
    secure: rZ2WjoUDzL3ZjbEuu/WA5g==
  artifact: /.*(\.)nupkg/
  on:
    branch: master
after_deploy:
- pwsh: ./publish-github-docker.ps1 $env:GH_TOKEN $env:APPVEYOR_BUILD_WORKER_IMAGE
