//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTiff2Tiles.Core.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GTiff2Tiles.Core.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already exist. Path:{1}.
        /// </summary>
        internal static string AlreadyExist {
            get {
                return ResourceManager.GetString("AlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory is empty. Please, select another directory. Path:{0}.
        /// </summary>
        internal static string DirectoryIsEmpty {
            get {
                return ResourceManager.GetString("DirectoryIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory isn&apos;t empty. Please, select another directory. Path:{0}.
        /// </summary>
        internal static string DirectoryIsntEmpty {
            get {
                return ResourceManager.GetString("DirectoryIsntEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} doesn&apos;t exist. Path:{1}.
        /// </summary>
        internal static string DoesntExist {
            get {
                return ResourceManager.GetString("DoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} doesn&apos;t support current platform.
        /// </summary>
        internal static string DoesntSupportPlatform {
            get {
                return ResourceManager.GetString("DoesntSupportPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is null.
        /// </summary>
        internal static string IsNull {
            get {
                return ResourceManager.GetString("IsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is lesser or equal {1}.
        /// </summary>
        internal static string LesserOrEqual {
            get {
                return ResourceManager.GetString("LesserOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is lesser, than {1}.
        /// </summary>
        internal static string LesserThan {
            get {
                return ResourceManager.GetString("LesserThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} string is empty.
        /// </summary>
        internal static string StringIsEmpty {
            get {
                return ResourceManager.GetString("StringIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add value to {0} collection.
        /// </summary>
        internal static string UnableToAddToCollection {
            get {
                return ResourceManager.GetString("UnableToAddToCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to calculate tile&apos;s coordinate borders.
        /// </summary>
        internal static string UnableToCalculateCoordinates {
            get {
                return ResourceManager.GetString("UnableToCalculateCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to configure {0}.
        /// </summary>
        internal static string UnableToConfigure {
            get {
                return ResourceManager.GetString("UnableToConfigure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to convert coordinates into tile numbers.
        /// </summary>
        internal static string UnableToConvertCoordinatesToTiles {
            get {
                return ResourceManager.GetString("UnableToConvertCoordinatesToTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create {0}. Path:{1}.
        /// </summary>
        internal static string UnableToCreate {
            get {
                return ResourceManager.GetString("UnableToCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create tile. X:{0}, Y:{1}.
        /// </summary>
        internal static string UnableToCreateTile {
            get {
                return ResourceManager.GetString("UnableToCreateTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get {0} coordinate borders or sizes.
        /// </summary>
        internal static string UnableToGetCoordinates {
            get {
                return ResourceManager.GetString("UnableToGetCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to join {0}. X:{1}, Y:{2}.
        /// </summary>
        internal static string UnableToJoin {
            get {
                return ResourceManager.GetString("UnableToJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open {0}. Path:{1}.
        /// </summary>
        internal static string UnableToOpen {
            get {
                return ResourceManager.GetString("UnableToOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to print {0} drivers.
        /// </summary>
        internal static string UnableToPrintDrivers {
            get {
                return ResourceManager.GetString("UnableToPrintDrivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} extension isn&apos;t {1}. Path:{2}.
        /// </summary>
        internal static string WrongExtension {
            get {
                return ResourceManager.GetString("WrongExtension", resourceCulture);
            }
        }
    }
}
