//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTiff2Tiles.Core.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GTiff2Tiles.Core.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} directory isn&apos;t empty. Please, select another directory. Path:{1}. Method:{2}.
        /// </summary>
        internal static string DirectoryIsntEmpty {
            get {
                return ResourceManager.GetString("DirectoryIsntEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} doesn&apos;t support current platform. Method:{1}.
        /// </summary>
        internal static string DoesntSupportPlatform {
            get {
                return ResourceManager.GetString("DoesntSupportPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} extension isn&apos;t {1}. Path:{2}. Method:{3}.
        /// </summary>
        internal static string ExtensionIsnt {
            get {
                return ResourceManager.GetString("ExtensionIsnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} isn&apos;t exist. Path:{1}. Method:{2}.
        /// </summary>
        internal static string IsntExist {
            get {
                return ResourceManager.GetString("IsntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is null. Method:{1}.
        /// </summary>
        internal static string IsNull {
            get {
                return ResourceManager.GetString("IsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is lesser or equal {1}. Method:{2}.
        /// </summary>
        internal static string LesserOrEqual {
            get {
                return ResourceManager.GetString("LesserOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is lesser, than {1}. Method:{2}.
        /// </summary>
        internal static string LesserThan {
            get {
                return ResourceManager.GetString("LesserThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} string is empty. Method:{1}.
        /// </summary>
        internal static string StringIsEmpty {
            get {
                return ResourceManager.GetString("StringIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add value to {0} dictionary. Method:{1}.
        /// </summary>
        internal static string UnableToAddToDictionary {
            get {
                return ResourceManager.GetString("UnableToAddToDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to calculate tile&apos;s coordinate borders. Method:{0}.
        /// </summary>
        internal static string UnableToCalculateCoordinates {
            get {
                return ResourceManager.GetString("UnableToCalculateCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to complete {0} method.
        /// </summary>
        internal static string UnableToComplete {
            get {
                return ResourceManager.GetString("UnableToComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to configure {0}. Method:{1}.
        /// </summary>
        internal static string UnableToConfigure {
            get {
                return ResourceManager.GetString("UnableToConfigure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to convert coordinates into tile numbers. Method:{0}.
        /// </summary>
        internal static string UnableToConvertCoordinatesToTiles {
            get {
                return ResourceManager.GetString("UnableToConvertCoordinatesToTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create {0}. Path:{1}. Method:{2}.
        /// </summary>
        internal static string UnableToCreate {
            get {
                return ResourceManager.GetString("UnableToCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create tile {0}. {1}:{2}, {3}:{4}. Method:{5}.
        /// </summary>
        internal static string UnableToCreateTile {
            get {
                return ResourceManager.GetString("UnableToCreateTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get {0} coordinate borders or sizes. Method:{1}.
        /// </summary>
        internal static string UnableToGetCoordinates {
            get {
                return ResourceManager.GetString("UnableToGetCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to join {0}. {1}:{2}, {3}:{4}. Method:{5}.
        /// </summary>
        internal static string UnableToJoin {
            get {
                return ResourceManager.GetString("UnableToJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is unable to open {2}. Path:{3}. Method:{4}.
        /// </summary>
        internal static string UnableToOpen {
            get {
                return ResourceManager.GetString("UnableToOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to print current {0} driver. Method:{1}.
        /// </summary>
        internal static string UnableToPrintDriver {
            get {
                return ResourceManager.GetString("UnableToPrintDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to print {0} drivers, because binary files wasn&apos;t found. Method:{1}.
        /// </summary>
        internal static string UnableToPrintDrivers {
            get {
                return ResourceManager.GetString("UnableToPrintDrivers", resourceCulture);
            }
        }
    }
}
