name: .NET Core CI

on: [push]

jobs:

# Build on Windows

  build-windows:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.201
    - name: Build with dotnet
      run: |
        echo Build win-x64 start
        dotnet build -c Release /p:Platform=x64
        
        echo Build win-x64 complete
        
# Publish core package to nuget

  publish-nuget:
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      # Required for a specific dotnet version that doesn't come with ubuntu-latest / windows-latest
      # Visit bit.ly/2synnZl to see the list of SDKs that are pre-installed with ubuntu-latest / windows-latest
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.201
      
      # Publish
      - name: publish on version change
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: GTiff2Tiles.Core/GTiff2Tiles.Core.csproj # Relative to repository root
          # VERSION_FILE_PATH: Directory.Build.props # Filepath with version info, relative to repository root. Defaults to project file
          # VERSION_REGEX: <Version>(.*)<\/Version> # Regex pattern to extract version info in a capturing group
          # TAG_COMMIT: true # Flag to enable / disalge git tagging
          # TAG_FORMAT: v* # Format of the git tag, [*] gets replaced with version
          NUGET_KEY: ${{secrets.NUGET_API_KEY}} # nuget.org API key
          PACKAGE_NAME: GTiff2Tiles
      
# Unit tests on Windows

  unit-tests-windows:
    
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.201
    - name: Run unit tests
      run: |
        echo Unit tests win-x64 start
        dotnet test -c Release /p:Platform=x64
        
        echo Unit tests win-x64 complete
        
# Build on Linux (Ubuntu)

  build-linux:

    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.201
    - name: Build with dotnet
      run: |
        echo Build linux-x64 core start
        dotnet build GTiff2Tiles.Core -c Release /p:Platform=x64

        echo Build linux-x64 benchmarks start
        dotnet build GTiff2Tiles.Benchmarks -c Release /p:Platform=x64

        echo Build linux-x64 console start
        dotnet build GTiff2Tiles.Console -c Release /p:Platform=x64

        echo Build linux-x64 tests start
        dotnet build GTiff2Tiles.Tests -c Release /p:Platform=x64
        
        echo Build linux-x64 complete
      
# Unit tests on Linux (Ubuntu)

  unit-tests-linux:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.201
    - name: Run unit tests
      run: |
        echo Unit tests linux-x64 start
        dotnet test GTiff2Tiles.Tests -c Release /p:Platform=x64

        echo Unit tests linux-x64 complete
