name: snyk-check-code
on:
  workflow_dispatch:
    inputs:
      runs-on:
        description: 'The operating system to run the job on'
        required: true
        type: choice
        options:
          - ubuntu-latest
          - windows-latest
          - macos-latest
      dotnet-version:
        description: 'dotnet sdk version'
        required: false
        type: string
        default: '8.x'
  workflow_call:
    inputs:
      runs-on:
        description: 'The operating system to run the job on'
        required: true
        type: string
      dotnet-version:
        description: 'dotnet sdk version'
        required: false
        type: string
        default: '8.x'
 
jobs:

  snyk:
    runs-on: ${{inputs.runs-on}}
    steps:
      - uses: actions/checkout@v4
        
      - name: snyk-setup
        uses: snyk/actions/setup@0.4.0
            
      - name: dotnet-setup
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{inputs.dotnet-version}}
        
      - name: snyk-auth
        run: snyk auth ${{secrets.SNYK_TOKEN}}
        
        # Runs Snyk Code (SAST) analysis
        # Use || true to not fail the pipeline
      - name: snyk-code-test
        run: snyk code test --sarif > snyk-code.sarif || true

        # Runs Snyk Open Source (SCA) analysis and uploads result to Snyk
        # probably fails due to DIrectory.Build.props not bein supported by snyk atm
      - name: snyk-monitor
        run: snyk monitor --all-projects || true

      - name: upload-security-report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk-code.sarif
      
